apiVersion: v1
kind: Namespace
metadata:
  name: flink
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  serviceName: "flink-jobmanager"
  replicas: 2  # Ensure redundancy
  selector:
    matchLabels:
      app: flink
      role: jobmanager
  template:
    metadata:
      labels:
        app: flink
        role: jobmanager
    spec:
      serviceAccountName: flink
      containers:
      - name: jobmanager
        image: flink:1.14
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-taskmanager
  namespace: flink
spec:
  serviceName: "flink-taskmanager"
  replicas: 5  # Scale based on job load
  selector:
    matchLabels:
      app: flink
      role: taskmanager
  template:
    metadata:
      labels:
        app: flink
        role: taskmanager
    spec:
      serviceAccountName: flink
      containers:
      - name: taskmanager
        image: flink:1.14
        ports:
        - containerPort: 6121
