apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
  namespace: spark
spec:
  serviceName: "spark-master"
  replicas: 3  # Increase for HA
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      serviceAccountName: spark
      containers:
      - name: master
        image: bitnami/spark:3.2.0
        ports:
        - containerPort: 7077
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  namespace: spark
spec:
  serviceName: "spark-worker"
  replicas: 5  # Scale workers based on load
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      serviceAccountName: spark
      containers:
      - name: worker
        image: bitnami/spark:3.2.0
        env:
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 15
