apiVersion: v1
kind: Namespace
metadata:
  name: trino
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino
  namespace: trino
spec:
  serviceName: "trino"
  replicas: 3  # For HA and scaling
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      serviceAccountName: trino
      containers:
      - name: trino
        image: trinodb/trino:latest
        ports:
        - containerPort: 8080
        #liveness
