apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  ports:
  - port: 8081
  selector:
    app: flink
    role: jobmanager
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  labels:
    app: flink
    role: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      role: jobmanager
  template:
    metadata:
      labels:
        app: flink
        role: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:1.13.0
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    role: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      role: taskmanager
  template:
    metadata:
      labels:
        app: flink
        role: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:1.13.0
        ports:
        - containerPort: 6121
        - containerPort: 6122
