version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    environment:
      - JAVA_OPTS="-Xms512m -Xmx1024m"
      - GIT_REF_NAME=main
    ports:
      - "19120:19120"
    volumes:
      - nessie_data:/var/nessie
    depends_on:
      - minio

  # Dremio (SQL query engine for data lake)
  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    environment:
      - DREMIO_ES_KAFKA_ENABLED=false
      - DREMIO_PORT=9047
      - DREMIO_ADMIN_PASSWORD=adminpassword
    ports:
      - "9047:9047"
      - "31010:31010"
    volumes:
      - dremio_data:/opt/dremio/data
    depends_on:
      - minio
      - nessie

volumes:
  minio_data:
  nessie_data:
  dremio_data:
