version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      # MINIO_REGION : "EU-TRK-001"
      # MINIO_ACCESS_KEY: "minioaccesskey"
      # MINIO_SECRET_KEY: "miniosecretkey"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    volumes:
      - nessie_data:/var/nessie
    depends_on:
      - minio

  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    environment:
      - DREMIO_ES_KAFKA_ENABLED=false
      - DREMIO_PORT=9047
      - DREMIO_ADMIN_PASSWORD=adminpassword
    # user: "dremio:dremio"
    ports:
      - "9047:9047"
      - "31010:31010"
    volumes:
      - dremio_data:/opt/dremio/data
    depends_on:
      - minio
      - nessie

volumes:
  minio_data:
  nessie_data:
  dremio_data:



# Go to localhost:9001 in your browser
# login with username/password = admin/password
# click on the buckets section on the menu to the left
# create a new bucket called warehouse

# Connect Dremio to Nessie/Minio
# Go to localhost:9047
# Setup your Dremio Account
# From dashboard click on "add source" in the bottom left
# Select "Nessie"
# On the "General" section add the following settings
# name: nessie
# Nessie Endpoint URL: http://nessie:19120/api/v2
# authentication: none
# On the "Storage" section add the following settings:
# Authentication Type: AWS Access Key
# AWS Access Key: admin
# AWS Secret Key: password
# AWS Root Path: /warehouse
# Connection Properties(name/value):
# fs.s3a.style.path.access = true
# fs.s3a.endpoint = minio:9000
# dremio.s3.compat = true
# encrypt connection: false
